In [38]:
#from __future__ import print_function
import keras
from keras.models import Sequential
from keras.datasets import mnist # minst is set of handwritten images
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D #  2d convolution can be 1D
from keras import backend as k 

In [39]:
import sys
import tensorflow as tf
import numpy as np
sys.version

'3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]'

In [40]:
batch_size = 128 #no of images in batch
num_classes = 10
epochs = 12

In [41]:
mydata= np.load('datasets/mnist.npz')
mydata['x_train']

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [42]:
x_train, y_train=mydata['x_train'], mydata['y_train']
x_test, y_test= mydata['x_test'], mydata['y_test']

In [43]:
# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
# Download Link - https://s3.amazonaws.com/img-datasets/mnist.npz
(x_train, y_train), (x_test, y_test) = mnist.load_data() 

In [44]:
k.image_data_format()

'channels_last'

In [45]:
if k.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

In [46]:
x_train=x_train.astype('float32')# 32 bit memory will be allocated to store float no
x_test=x_test.astype('float32')
x_train/=255
x_test/=255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples


In [47]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [48]:
# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [49]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [50]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5 # drop randomly 5 % of weights from 2 layers of hidden structure  
model.add(Dense(num_classes, activation='softmax'))

In [54]:
print(keras.__version__)
print(tf.__version__)

2.2.4
1.11.0


In [55]:
model.compile (loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 12, 12, 64)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 12, 12, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 9216)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               1179776   
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0         
__________

In [56]:

model.fit(x_train, y_train, batch_size, epochs=epochs, verbose=1, validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 558s 9ms/step - loss: 0.2636 - acc: 0.9193 - val_loss: 0.0633 - val_acc: 0.9796
Epoch 2/12
60000/60000 [==============================] - 303s 5ms/step - loss: 0.0923 - acc: 0.9730 - val_loss: 0.0461 - val_acc: 0.9856
Epoch 3/12
60000/60000 [==============================] - 299s 5ms/step - loss: 0.0682 - acc: 0.9795 - val_loss: 0.0356 - val_acc: 0.9879
Epoch 4/12
60000/60000 [==============================] - 304s 5ms/step - loss: 0.0541 - acc: 0.9836 - val_loss: 0.0334 - val_acc: 0.9894
Epoch 5/12
60000/60000 [==============================] - 300s 5ms/step - loss: 0.0481 - acc: 0.9854 - val_loss: 0.0279 - val_acc: 0.9909
Epoch 6/12
60000/60000 [==============================] - 333s 6ms/step - loss: 0.0408 - acc: 0.9879 - val_loss: 0.0309 - val_acc: 0.9903
Epoch 7/12
60000/60000 [==============================] - 14284s 238ms/step - loss: 0.0387 - acc: 0.9881 - val_loss: 0.030

In [57]:
score=model.evaluate(x_test, y_test, verbose=0)
print('test loss:', score[0])
print('Test accuracy', score[1])

test loss: 0.02808454699868544
Test accuracy 0.9911


In [ ]:
model.save('.\model\myModel_MNIST.h5')